export default {
  costMultiplier: 1.15,
  items: [
    { id: 'passiveMaker', name: 'The Gub', baseCost: 100, rate: 1 },
    { id: 'guberator', name: 'Guberator', baseCost: 500, rate: 5 },
    { id: 'gubmill', name: 'Gubmill', baseCost: 2000, rate: 20 },
    { id: 'gubsolar', name: 'Solar Gub Panels', baseCost: 10000, rate: 100 },
    {
      id: 'gubfactory',
      name: 'Gubactory',
      baseCost: 50000,
      rate: 500,
      image: 'small_gub_03_Gorpa.png',
    },
    { id: 'gubhydro', name: 'Hydro Gub Plant', baseCost: 250000, rate: 2500 },
    {
      id: 'gubnuclear',
      name: 'Nuclear Gub Plant',
      baseCost: 1000000,
      rate: 10000,
    },
    {
      id: 'gubquantum',
      name: 'Quantum Gub Computer',
      baseCost: 5000000,
      rate: 50000,
    },
    {
      id: 'gubai',
      name: 'GUB AI',
      caption: '(be careful of gubnet...)',
      baseCost: 25000000,
      rate: 250000,
    },
    {
      id: 'gubclone',
      name: 'Gub Cloning Facility',
      baseCost: 125000000,
      rate: 1250000,
      costMultiplier: 1.1,
    },
    {
      id: 'gubspace',
      name: 'Gub Space Program',
      baseCost: 625000000,
      rate: 6250000,
      image: 'small_gub_02_Glurp.png',
      costMultiplier: 1.3,
    },
    {
      id: 'intergalactic',
      name: 'Intergalactic Gub',
      baseCost: 3125000000,
      rate: 31250000,
      image: 'small_gub_01_gluburple.png',
      costMultiplier: 1.6,
    },
  ],
  upgrades: [
    {
      id: 'upg1',
      name: 'Gub item #1',
      target: 'passiveMaker',
      multiplier: 2,
      cost: 10000,
      unlockAt: 25,
      image: 'small_gub_04_GubsUp.png',
      modifier: '+100% The Gub production',
      description: 'Placeholder description',
    },
    {
      id: 'upg2',
      name: 'Gub item #2',
      target: 'guberator',
      multiplier: 2,
      cost: 50000,
      unlockAt: 25,
      image: 'small_gub_05_GubShy.png',
      modifier: '+100% Guberator production',
      description: 'Placeholder description',
    },
    {
      id: 'upg3',
      name: 'Gub item #3',
      target: 'gubmill',
      multiplier: 2,
      cost: 200000,
      unlockAt: 25,
      image: 'small_gub_06_GubsComfy.png',
      modifier: '+100% Gubmill production',
      description: 'Placeholder description',
    },
    {
      id: 'upg4',
      name: 'Gub item #4',
      target: 'gubsolar',
      multiplier: 2,
      cost: 1000000,
      unlockAt: 25,
      image: 'small_gub_11_Grizz.png',
      modifier: '+100% Solar Gub Panels production',
      description: 'Placeholder description',
    },
    {
      id: 'upg5',
      name: 'Gub item #5',
      target: 'gubfactory',
      multiplier: 2,
      cost: 5000000,
      unlockAt: 25,
      image: 'small_gub_09_gubgub.png',
      modifier: '+100% Gubactory production',
      description: 'Placeholder description',
    },
  ],
};
